# Generated by cpp11: do not edit by hand

HILBERT_index_ <- function(n, x, y) {
  .Call(`_hilbert_HILBERT_index_`, n, x, y)
}

HILBERT_position_ <- function(n, h) {
  .Call(`_hilbert_HILBERT_position_`, n, h)
}

HILBERT_coords_to_xy_ <- function(n, x, y, extent) {
  .Call(`_hilbert_HILBERT_coords_to_xy_`, n, x, y, extent)
}

HILBERT_xy_to_coords_ <- function(n, x, y, extent) {
  .Call(`_hilbert_HILBERT_xy_to_coords_`, n, x, y, extent)
}
