# Generated by cpp11: do not edit by hand

index <- function(n, x, y) {
  .Call(`_hilbert_index`, n, x, y)
}

position <- function(n, h) {
  .Call(`_hilbert_position`, n, h)
}

coords_to_xy <- function(n, x, y, extent) {
  .Call(`_hilbert_coords_to_xy`, n, x, y, extent)
}

xy_to_coords <- function(n, x, y, extent) {
  .Call(`_hilbert_xy_to_coords`, n, x, y, extent)
}
